Repository megaease/easegress, pull requests merged in 2021-08, with the labels that each got.

#157 add start script retry
  example/sbin/start.sh
Labels: bug

#153 [filter] refactor apiaggregator
  doc/filters.md
  pkg/context/httptemplate.go
  pkg/filter/apiaggregator/apiaggregator.go
  pkg/object/rawconfigtrafficcontroller/rawconfigtrafficcontroller.go
Labels: enhancement

#163 [bug] fix http template dict empty error
  pkg/object/httppipeline/httppipeline.go
Labels: bug

#162 Readme
  README.md
Labels: documentation

#156 add unit tests
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/layout_test.go
  pkg/cluster/member_test.go
  pkg/common/lazybuf.go
  pkg/common/os_test.go
  pkg/common/sample.go
  pkg/common/signal_unix_test.go
  pkg/common/stat_aggregator_test.go
  pkg/common/sys_proc_linux.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/context/contexttest/context.go
  pkg/context/contexttest/request.go
  pkg/context/contexttest/response.go
  pkg/filter/canary/matcher_test.go
  pkg/filter/circuitbreaker/circuitbreaker.go
  pkg/filter/circuitbreaker/circuitbreaker_test.go
  pkg/filter/corsadaptor/corsadaptor_test.go
  pkg/filter/fallback/fallback_test.go
  pkg/filter/mock/mock.go
  pkg/filter/mock/mock_test.go
  pkg/filter/proxy/compression.go
  pkg/filter/proxy/compression_test.go
  pkg/filter/proxy/masterslavereader_test.go
  pkg/filter/proxy/proxy.go
  pkg/filter/proxy/request_test.go
  pkg/filter/proxy/server.go
  pkg/filter/proxy/server_test.go
  pkg/filter/responseadaptor/responseadaptor.go
  pkg/filter/responseadaptor/responseadaptor_test.go
  pkg/filter/timelimiter/timelimiter_test.go
  pkg/filter/validator/oauth2.go
  pkg/filter/validator/validator_test.go
  pkg/logger/logger.go
  pkg/object/function/spec/function_test.go
  pkg/object/meshcontroller/spec/spec_test.go
  pkg/object/statussynccontroller/timer_test.go
  pkg/util/jmxtool/agent_controller.go
  pkg/util/jmxtool/agent_controller_test.go
  pkg/util/jmxtool/common.go
  pkg/util/jmxtool/common_test.go
Labels: enhancement

#170 add unit tests
  go.mod
  go.sum
  pkg/cluster/cluster_test.go
  pkg/cluster/member.go
  pkg/cluster/member_test.go
  pkg/common/callback.go
  pkg/common/callback_test.go
  pkg/common/stat_aggregator.go
  pkg/common/stat_aggregator_test.go
  pkg/common/strings.go
  pkg/common/strings_test.go
  pkg/common/utils.go
  pkg/common/utils_test.go
  pkg/common/uuid.go
  pkg/context/contexttest/context.go
  pkg/filter/fallback/fallback_test.go
  pkg/filter/mock/mock.go
  pkg/filter/mock/mock_test.go
  pkg/filter/proxy/pool.go
  pkg/filter/proxy/proxy.go
  pkg/filter/proxy/proxy_test.go
  pkg/util/jmxtool/jmx_controller.go
  pkg/util/jmxtool/jmx_controller_test.go
  pkg/util/jsontool/jsontool_test.go
  pkg/util/ratelimiter/ratelimiter_test.go
  pkg/util/texttemplate/texttemplate_test.go
  pkg/util/urlrule/urlrule_test.go
Labels: enhancement

#155 Add documentation of user cases
  README.md
  doc/cookbook/README.md
  doc/cookbook/api_aggregator.md
  doc/cookbook/distributed_tracing.md
  doc/cookbook/faas.md
  doc/cookbook/flash_sale.md
  doc/cookbook/k8s_ingress_controller.md
  doc/cookbook/load_balancer.md
  doc/cookbook/performance.md
  doc/cookbook/resilience.md
  doc/cookbook/security.md
  doc/cookbook/service_proxy.md
  doc/cookbook/wasm.md
  doc/cookbook/workflow.md
  doc/filters.md
Labels: documentation

#173 [cluster] fix double close embed etcd clients peers
  pkg/cluster/cluster.go
Labels: enhancement

#175 fix links for user cases
  README.md
Labels: documentation

#178 simplify http fliter check
  pkg/util/httpfilter/httpfilter.go
Labels: enhancement

#164 [bug] fix interface nil convert panic
  pkg/object/trafficcontroller/trafficcontroller.go
Labels: bug

#181 [typo] fix typo in comments & const value(SignalUsr2)
  cmd/server/main.go
  pkg/common/signal.go
  pkg/common/signal_unix.go
  pkg/common/signal_unix_test.go
  pkg/context/httpcontext.go
  pkg/context/httprequest.go
  pkg/context/httpresponse.go
  pkg/context/httptemplate.go
  pkg/filter/proxy/pool.go
  pkg/filter/proxy/server.go
  pkg/graceupdate/graceupdate.go
  pkg/object/httpserver/mux.go
  pkg/supervisor/spec.go
  pkg/util/circuitbreaker/circuitbreaker.go
  pkg/util/httpheader/httpheader.go
  pkg/util/ipfilter/ipfilter.go
  pkg/util/jmxtool/agent_controller_test.go
  pkg/util/sem/semaphore.go
  pkg/util/texttemplate/texttemplate.go
Labels: enhancement

#176 [doc] add pipeline.md
  README.md
  doc/cookbook/README.md
  doc/cookbook/pipeline.md
Labels: documentation

#184 [doc] typo
  doc/cookbook/service_proxy.md
Labels: documentation

#186 [util]skip invalid ip cidr parse result
  pkg/util/ipfilter/ipfilter.go
Labels: enhancement

#183 [mesh] clean dead instance records
  pkg/object/meshcontroller/master/master.go
Labels: enhancement

#122 [doc] add benchmark.md
  doc/benchmark.md
  doc/stress-test-p99-latency.png
  doc/stress-test-rps.png
Labels: documentation

#217 avoid send duplicated metrics data (close #215)
  pkg/object/easemonitormetrics/easemonitormetrics.go
  pkg/object/statussynccontroller/statussynccontroller.go
  pkg/util/timetool/distributedtimer.go
Labels: bug

#188 add host functions for cluster data (flash sale support)
  cmd/client/command/common.go
  cmd/client/command/wasm.go
  doc/cookbook/flash_sale.md
  doc/cookbook/wasm.md
  doc/wasmhost.md
  go.mod
  go.sum
  pkg/api/wasm.go
  pkg/cluster/cluster_interface.go
  pkg/cluster/cluster_test.go
  pkg/cluster/layout.go
  pkg/cluster/layout_test.go
  pkg/cluster/op.go
  pkg/filter/bridge/bridge.go
  pkg/filter/wasmhost/hostfunc.go
  pkg/filter/wasmhost/vm.go
  pkg/filter/wasmhost/wasmhost.go
  pkg/object/httppipeline/httppipeline.go
  pkg/object/httppipeline/spec.go
Labels: documentation, enhancement
