Repository megaease/easegress, pull requests merged in 2021-09, with the labels that each got.

#224 fix test, random order of slice cause test fail
  pkg/filter/proxy/server_test.go
Labels: bug

#225 [build] change go image from alpine to 1.16-alpine
  build/package/Dockerfile
Labels: dependencies

#226 [build] rollback alpine:latest to 3.13 for stablebility
  build/package/Dockerfile
  build/package/Dockerfile.goreleaser
Labels: dependencies

#232 fix: the wrong link for ingress controller guide
  doc/cookbook/k8s_ingress_controller.md
Labels: documentation

#236 example typo
  example/README.md
  example/config/func-mirror.yaml
Labels: documentation

#230 improve egctl to support sending multi configs at once (fix #29)
  cmd/client/command/common.go
  cmd/client/command/object.go
  cmd/client/command/visitor.go
  cmd/client/command/wasm.go
Labels: enhancement

#242 fix lint warning
  cmd/client/command/visitor.go
  pkg/api/wasm.go
  pkg/common/os_test.go
  pkg/common/signal_unix.go
  pkg/common/signal_unix_test.go
  pkg/common/signal_windows.go
  pkg/common/time_unix.go
  pkg/common/time_windows.go
  pkg/filter/wasmhost/hostfunc.go
  pkg/filter/wasmhost/vm.go
  pkg/filter/wasmhost/wasmhost.go
Labels: enhancement

#245 update func match() in pkg/object/httpserver/mux.go
  pkg/object/httpserver/mux.go
Labels: enhancement

#247 add license checker
  .github/workflows/license-checker.yml
  .licenserc.yaml
  pkg/api/dynamicmux.go
  pkg/object/consulserviceregistry/client.go
  pkg/object/function/worker/worker.go
  pkg/object/meshcontroller/worker/api.go
  pkg/object/meshcontroller/worker/api_consul.go
  pkg/object/meshcontroller/worker/api_eureka.go
  pkg/object/meshcontroller/worker/api_nacos.go
  pkg/object/meshcontroller/worker/egress.go
  pkg/object/meshcontroller/worker/ingress.go
  pkg/object/meshcontroller/worker/observability.go
  pkg/object/meshcontroller/worker/server.go
  pkg/util/contexttool/contexttool.go
  pkg/util/yamltool/yamltool.go
Labels: github_actions

#249 [bugfix] correct update restfulapi in ctl
  cmd/client/command/object.go
Labels: bug

#246 Support mock service in mesh
  go.mod
  go.sum
  pkg/object/meshcontroller/api/api.go
  pkg/object/meshcontroller/api/api_part.go
  pkg/object/meshcontroller/spec/spec.go
  pkg/object/meshcontroller/spec/spec_test.go
  pkg/object/meshcontroller/worker/worker.go
Labels: enhancement

#261 [bot] change interval to monthly
  .github/dependabot.yml
Labels: dependencies

#269 fix bugs in custom object
  go.mod
  go.sum
  pkg/object/meshcontroller/api/api.go
  pkg/object/meshcontroller/api/api_customresource.go
  pkg/object/meshcontroller/layout/layout.go
  pkg/object/meshcontroller/service/service.go
  pkg/object/meshcontroller/spec/spec.go
  pkg/object/meshcontroller/spec/spec_test.go
Labels: bug

#267 [doc] add readme in cn
  README.zh-CN.md
Labels: documentation

#273 [bug] mesh master fix missing clean routine
  pkg/object/meshcontroller/master/master.go
Labels: bug

#274 [mesh] canceling the unnecessary goroutine using
  pkg/object/meshcontroller/master/master.go
Labels: enhancement

#276 [mesh] add consul empty checker
  pkg/object/meshcontroller/registrycenter/consul.go
Labels: bug

#278 update cluster example, no std-log-level in option
  doc/benchmark.md
  example/reader-004/conf/config.yaml
  example/reader-005/conf/config.yaml
  example/sbin/conf/config.yaml
  example/writer-001/conf/config.yaml
  example/writer-002/conf/config.yaml
  example/writer-003/conf/config.yaml
Labels: documentation

#254 chart: add chart files for helm-install
  helm-charts/ingress-controller/Chart.yaml
  helm-charts/ingress-controller/README.md
  helm-charts/ingress-controller/templates/ClusterRole.yaml
  helm-charts/ingress-controller/templates/ClusterRoleBinding.yaml
  helm-charts/ingress-controller/templates/ConfigMap.yaml
  helm-charts/ingress-controller/templates/Deployment.yaml
  helm-charts/ingress-controller/templates/IngressClass.yaml
  helm-charts/ingress-controller/templates/Service.yaml
  helm-charts/ingress-controller/templates/ServiceAccount.yaml
  helm-charts/ingress-controller/values.yaml
Labels: dependencies

#280 [Mesh] fixing deadlock and optimizing mesh controller's master
  pkg/object/meshcontroller/master/master.go
  pkg/object/meshcontroller/worker/egress.go
  pkg/object/meshcontroller/worker/ingress.go
Labels: bug

#250 Update doc/developer-guide.md
  doc/developer-guide.md
  pkg/supervisor/registry.go
Labels: documentation

#287 [mesh] fix easemesh bug #92
  pkg/object/meshcontroller/registrycenter/registry.go
  pkg/object/meshcontroller/worker/worker.go
Labels: bug
