Repository megaease/easegress, pull requests merged in 2021-06, with the labels that each got.

#38 Chore: update dependencies
  go.mod
  go.sum
  pkg/cluster/cluster.go
  pkg/cluster/cluster_interface.go
  pkg/cluster/config.go
  pkg/cluster/member.go
  pkg/cluster/member_test.go
  pkg/cluster/mutex.go
  pkg/cluster/op.go
  pkg/cluster/syncer.go
  pkg/cluster/watcher.go
  pkg/object/meshcontroller/informer/informer.go
  pkg/object/meshcontroller/registrycenter/discovery.go
  pkg/object/meshcontroller/service/service.go
  pkg/object/meshcontroller/storage/storage.go
  pkg/object/serviceregistry/etcdserviceregistry/etcdserviceregistry.go
Labels: enhancement

#44 Chore: refine Makefile
  Makefile
Labels: enhancement

#48 Add multiple certs support, close #31
  pkg/object/httpserver/spec.go
Labels: enhancement

#50 [option] fix print helper msg twice bug, close #37
  pkg/option/option.go
Labels: bug

#52 Add Easegress Logo
  README.md
  doc/easegress.svg
Labels: documentation

#45 Docker: add tzdata package for latest alpine
  Dockerfile
  build/package/Dockerfile
  build/package/Dockerfile.goreleaser
  release/build-client-image.sh
  release/build-server-image.sh
Labels: enhancement

#43 Deps: use dependabot to update dependencies
  .github/dependabot.yml
Labels: enhancement

#59 FaaSController
  doc/faascontroller.md
  go.mod
  go.sum
  pkg/object/function/cronjob.go
  pkg/object/function/faascontroller.go
  pkg/object/function/function.go
  pkg/object/function/provider/provider.go
  pkg/object/function/spec/fsm.go
  pkg/object/function/spec/fsm_test.go
  pkg/object/function/spec/function.go
  pkg/object/function/spec/function_test.go
  pkg/object/function/storage/storage.go
  pkg/object/function/worker/api.go
  pkg/object/function/worker/function.go
  pkg/object/function/worker/ingress.go
  pkg/object/function/worker/worker.go
  pkg/object/httpserver/mux.go
  pkg/object/meshcontroller/master/api_serviceinstance.go
  pkg/object/meshcontroller/master/master.go
  pkg/object/meshcontroller/registrycenter/registry.go
  pkg/object/meshcontroller/spec/spec.go
  pkg/object/meshcontroller/worker/ingress.go
Labels: enhancement

#76 [bug] fix issue#73 httpserver 404 without headers
  pkg/object/httpserver/mux.go
Labels: bug

#85 Support strip trailing slash
  pkg/api/server.go
Labels: enhancement

#87 fix double free etcd
  pkg/cluster/cluster.go
Labels: bug

#86 chore: remove unnecessary condition
  pkg/object/meshcontroller/informer/informer.go
Labels: enhancement

#91 [release] add change log, update dependabot interval
  .github/dependabot.yml
  CHANGELOG.md
  doc/Roadmap.md
Labels: documentation

#92 [doc] keep content style consistency
  CHANGELOG.md
Labels: documentation

#93 Fix typo
  doc/Roadmap.md
  doc/developer-guide.md
  doc/filters.md
  example/README.md
  pkg/cluster/cluster.go
  pkg/cluster/doc.go
  pkg/cluster/member.go
  pkg/cluster/syncer.go
  pkg/context/httpcontext.go
  pkg/context/httptemplate.go
  pkg/filter/apiaggregator/apiaggregator.go
  pkg/filter/bridge/bridge.go
  pkg/filter/canary/matcher.go
  pkg/filter/circuitbreaker/circuitbreaker.go
  pkg/filter/fallback/fallback.go
  pkg/filter/proxy/proxy.go
  pkg/filter/proxy/server.go
  pkg/filter/ratelimiter/ratelimiter.go
  pkg/filter/remotefilter/remotefilter.go
  pkg/filter/retryer/retryer.go
  pkg/filter/timelimiter/timelimiter.go
  pkg/filter/validator/jwt.go
  pkg/graceupdate/graceupdate.go
  pkg/logger/logger.go
  pkg/object/easemonitormetrics/easemonitormetrics.go
  pkg/object/function/provider/provider.go
  pkg/object/function/worker/api.go
  pkg/object/httppipeline/httppipeline.go
  pkg/object/httpserver/httpserver.go
  pkg/object/httpserver/mux.go
  pkg/object/httpserver/runtime.go
  pkg/object/httpserver/spec.go
  pkg/object/meshcontroller/registrycenter/nacos.go
  pkg/object/meshcontroller/registrycenter/registry.go
  pkg/object/meshcontroller/worker/api.go
  pkg/object/meshcontroller/worker/api_consul.go
  pkg/object/meshcontroller/worker/api_eureka.go
  pkg/object/meshcontroller/worker/api_nacos.go
  pkg/object/statussynccontroller/statussynccontroller.go
  pkg/supervisor/registry.go
  pkg/util/circuitbreaker/circuitbreaker.go
  pkg/util/codecounter/codecounter.go
  pkg/util/fallback/fallback.go
  pkg/util/httpheader/validator.go
  pkg/util/jmxtool/jmx_controller.go
  pkg/util/memorycache/memorycache.go
  pkg/util/signer/spec.go
  pkg/util/texttemplate/texttemplate.go
  pkg/util/urlrule/urlrule.go
  pkg/v/format.go
  pkg/v/v.go
Labels: documentation
