Repository megaease/easegress, pull requests merged in 2021-07, with the labels that each got.

#77 CI: check unnecessary dependencies
  .github/workflows/test.yml
  Makefile
Labels: enhancement

#96 Support dynamic admin API && correct syncer && make interface cleaner
  Makefile
  cmd/server/main.go
  example/sbin/status.sh
  pkg/api/api.go
  pkg/api/cluster.go
  pkg/api/dynamicmux.go
  pkg/api/member.go
  pkg/api/metadata.go
  pkg/api/middlewares.go
  pkg/api/object.go
  pkg/api/server.go
  pkg/cluster/cluster.go
  pkg/cluster/syncer.go
  pkg/filter/apiaggregator/apiaggregator.go
  pkg/filter/bridge/bridge.go
  pkg/filter/circuitbreaker/circuitbreaker.go
  pkg/filter/corsadaptor/corsadaptor.go
  pkg/filter/fallback/fallback.go
  pkg/filter/mock/mock.go
  pkg/filter/proxy/proxy.go
  pkg/filter/ratelimiter/ratelimiter.go
  pkg/filter/remotefilter/remotefilter.go
  pkg/filter/requestadaptor/requestadaptor.go
  pkg/filter/responseadaptor/responseadaptor.go
  pkg/filter/retryer/retryer.go
  pkg/filter/timelimiter/timelimiter.go
  pkg/filter/validator/validator.go
  pkg/object/easemonitormetrics/easemonitormetrics.go
  pkg/object/function/faascontroller.go
  pkg/object/function/worker/api.go
  pkg/object/function/worker/ingress.go
  pkg/object/function/worker/worker.go
  pkg/object/httppipeline/httppipeline.go
  pkg/object/httppipeline/registry.go
  pkg/object/httppipeline/spec.go
  pkg/object/httpserver/httpserver.go
  pkg/object/httpserver/mux.go
  pkg/object/httpserver/runtime.go
  pkg/object/meshcontroller/api/api.go
  pkg/object/meshcontroller/ingresscontroller/ingresscontroller.go
  pkg/object/meshcontroller/master/master.go
  pkg/object/meshcontroller/meshcontroller.go
  pkg/object/meshcontroller/registrycenter/discovery.go
  pkg/object/meshcontroller/service/service.go
  pkg/object/meshcontroller/spec/spec.go
  pkg/object/meshcontroller/worker/worker.go
  pkg/object/rawconfigtrafficcontroller/rawconfigtrafficcontroller.go
  pkg/object/serviceregistry/consulserviceregistry/consulserviceregistry.go
  pkg/object/serviceregistry/etcdserviceregistry/etcdserviceregistry.go
  pkg/object/serviceregistry/eurekaserviceregistry/eurekaserviceregistry.go
  pkg/object/serviceregistry/zookeeperserviceregistry/zookeeperserviceregistry.go
  pkg/object/statussynccontroller/statussynccontroller.go
  pkg/object/trafficcontroller/trafficcontroller.go
  pkg/supervisor/configsyncer.go
  pkg/supervisor/object.go
  pkg/supervisor/registry.go
  pkg/supervisor/spec.go
  pkg/supervisor/supervisor.go
  pkg/v/v.go
Labels: enhancement

#105 Add missing `return err` after `if err == <ErrorType>` statement.
  pkg/object/meshcontroller/worker/egress.go
  pkg/object/meshcontroller/worker/ingress.go
Labels: bug

#106 [bug] revert PR #105 and add comment
  pkg/object/meshcontroller/worker/egress.go
  pkg/object/meshcontroller/worker/ingress.go
Labels: bug

#100 Use default spec coorectly & fix httppipeline.Validate without recursively checking
  go.mod
  go.sum
  pkg/api/object.go
  pkg/object/function/faascontroller.go
  pkg/object/function/worker/api.go
  pkg/object/function/worker/ingress.go
  pkg/object/httppipeline/httppipeline.go
  pkg/object/httppipeline/spec.go
  pkg/object/httpserver/mux.go
  pkg/object/httpserver/spec.go
  pkg/object/meshcontroller/api/api.go
  pkg/object/meshcontroller/spec/spec.go
  pkg/object/meshcontroller/worker/egress.go
  pkg/object/serviceregistry/consulserviceregistry/consulserviceregistry.go
  pkg/object/serviceregistry/zookeeperserviceregistry/zookeeperserviceregistry.go
  pkg/supervisor/spec.go
  pkg/util/yamltool/yamltool.go
  pkg/v/v.go
  pkg/v/validaterecorder.go
Labels: bug

#101 Add controllers documentation
  doc/controllers.md
  doc/filters.md
  example/config/zookeeper-service-registry-example.yaml
Labels: documentation

#109 [mesh] convert service instance API to pb/json
  go.mod
  go.sum
  pkg/object/meshcontroller/api/api_part.go
  pkg/object/meshcontroller/api/api_serviceinstance.go
Labels: enhancement

#110 Fix unit test failure of semaphore and cluster
  go.mod
  pkg/cluster/cluster_test.go
  pkg/cluster/member_test.go
  pkg/object/httpserver/listen.go
  pkg/util/sem/semaphore.go
  pkg/util/sem/semaphore_test.go
Labels: bug

#102 add kubernetes ingress controller (close #25)
  README.md
  doc/controllers.md
  doc/ingresscontroller.md
  go.mod
  pkg/object/httpserver/spec.go
  pkg/object/ingresscontroller/ingresscontroller.go
  pkg/object/ingresscontroller/k8s.go
  pkg/object/ingresscontroller/translator.go
  pkg/registry/registry.go
Labels: enhancement

#115 fix bug #114
  pkg/object/httpserver/listen.go
  pkg/util/sem/semaphore.go
Labels: bug

#116 add filter WasmHost (close #1)
  Makefile
  README.md
  doc/filters.md
  doc/reference.md
  example/backend-service/mirror/mirror.go
  go.mod
  go.sum
  pkg/api/api.go
  pkg/api/wasm.go
  pkg/cluster/layout.go
  pkg/cluster/op.go
  pkg/filter/wasmhost/doc.go
  pkg/filter/wasmhost/hostfunc.go
  pkg/filter/wasmhost/vm.go
  pkg/filter/wasmhost/wasmhost.go
  pkg/registry/registry.go
Labels: enhancement

#123 [release] v1.1.0
  .goreleaser.yml
  Makefile
  README.md
Labels: documentation

#125 [doc] update changelog
  CHANGELOG.md
Labels: documentation

#132 Add github action for code analysis & fix the spelling & lint issues
  .github/workflows/code.analysis.yml
  example/sbin/README.md
  pkg/object/function/spec/fsm.go
  pkg/object/httppipeline/httppipeline.go
  pkg/util/circuitbreaker/circuitbreaker.go
  pkg/util/jmxtool/jmx_controller.go
Labels: enhancement

#134 [doc] update logo and readme
  README.md
  doc/easegress.svg
Labels: documentation

#135 Modified the logo position and add the notes for service mesh
  README.md
Labels: documentation

#136 add egctl command for wasm
  cmd/client/command/common.go
  cmd/client/command/wasm.go
  cmd/client/main.go
Labels: enhancement

#130 [pr-test]add basic httpsvr+pipeline test
  build/test/httpserver_test.sh
Labels: enhancement

#103 WebSocket support close #99
  example/config/websocket-server-example.yaml
  go.mod
  pkg/object/websocketserver/proxy.go
  pkg/object/websocketserver/spec.go
  pkg/object/websocketserver/websocket.go
  pkg/registry/registry.go
Labels: enhancement

#137 [prtest] add retry limit
  build/test/httpserver_test.sh
Labels: bug

#139 [chores] remove unnecessary files and add texttemplate test
  cmd/client/command/mesh.go
  cmd/client/command/mesh_ingress.go
  cmd/client/command/mesh_service.go
  cmd/client/command/mesh_service_instance.go
  cmd/client/command/mesh_service_observability.go
  cmd/client/command/mesh_tenant.go
  cmd/client/main.go
  pkg/common/go.go
  pkg/common/go_test.go
  pkg/common/option.go
  pkg/common/option_test.go
  pkg/object/websocketserver/websocket.go
  pkg/util/texttemplate/texttemplate_test.go
Labels: dependencies

#138 add user-guide for WasmHost
  doc/filters.md
  doc/wasmhost.md
Labels: documentation

#140 fix compile error
  pkg/api/wasm.go
Labels: bug

#142 [pr-test] add exist 0 for Jenkins pipeline
  build/test/httpserver_test.sh
  example/backend-service/echo/echo.go
  example/clean_cluster.sh
Labels: bug

#150 Jwt pkg version update
  go.mod
  go.sum
  pkg/filter/canary/matcher.go
  pkg/filter/validator/jwt.go
  pkg/filter/validator/oauth2.go
Labels: dependencies

#144 [mesh] fix initTrafficGate panic when service not found
  pkg/object/meshcontroller/worker/worker.go
Labels: bug

#143 add more wasm host functions and support `wasm_init`
  doc/filters.md
  doc/wasmhost.md
  pkg/filter/wasmhost/hostfunc.go
  pkg/filter/wasmhost/vm.go
  pkg/filter/wasmhost/wasmhost.go
Labels: enhancement
